"""The fixtures must still be the bytes they are named for.

Most of this suite asks whether the reader agrees with PyVista. This file asks
a question underneath that one: whether the files being fed to both readers are
still the files the tests were written against.

It exists because one of the conformance tests cannot tell. ``mock.frd``,
``mock_crlf.frd`` and ``mock_cr.frd`` are the same document in three line-ending
encodings, and ``test_newline_variants_read_identically`` reads all three and
requires the same arrays out of each. If something normalised the line endings
-- git is the obvious candidate; ``core.autocrlf=true`` is what the Git for
Windows installer sets by default -- then all three files become LF, they are
identical, and that test passes *because* its subject was destroyed. A green
run would mean the opposite of what it appears to mean.

``.gitattributes`` marks ``*.frd`` binary so this cannot happen. This file is
the detector for the case where that line is removed, or where a fixture is
regenerated by a tool that does its own normalising, and it is a plain byte
count rather than anything cleverer so that it keeps working when the reader
does not.
"""

from __future__ import annotations

from tests.conftest import FIXTURE_DIR


def _endings(raw: bytes) -> tuple[int, int, int]:
    """Count CRLF pairs, then the CR and LF that are not part of one."""
    crlf = raw.count(b'\r\n')
    lone_cr = raw.count(b'\r') - crlf
    lone_lf = raw.count(b'\n') - crlf
    return crlf, lone_cr, lone_lf


def test_the_lf_fixture_is_lf_only():
    crlf, lone_cr, lone_lf = _endings((FIXTURE_DIR / 'mock.frd').read_bytes())
    assert (crlf, lone_cr) == (0, 0), 'mock.frd has picked up carriage returns'
    assert lone_lf > 0, 'mock.frd has no line endings at all'


def test_the_crlf_fixture_is_still_crlf():
    crlf, lone_cr, lone_lf = _endings((FIXTURE_DIR / 'mock_crlf.frd').read_bytes())
    assert crlf > 0, (
        'mock_crlf.frd has no CRLF left -- something normalised it, and '
        'test_newline_variants_read_identically is now comparing three copies '
        'of the same LF file and passing for that reason'
    )
    assert (lone_cr, lone_lf) == (0, 0), 'mock_crlf.frd has mixed endings'


def test_the_cr_fixture_is_still_cr_only():
    crlf, lone_cr, lone_lf = _endings((FIXTURE_DIR / 'mock_cr.frd').read_bytes())
    assert lone_cr > 0, (
        'mock_cr.frd has no lone carriage returns left -- see the note in '
        'test_the_crlf_fixture_is_still_crlf'
    )
    assert (crlf, lone_lf) == (0, 0), 'mock_cr.frd is no longer CR-only'


def test_the_three_variants_really_are_the_same_document():
    """Different bytes, same content: the premise the parity test relies on.

    Without this, the three fixtures could drift apart and the comparison
    between them would be testing two different documents rather than two
    encodings of one.
    """

    def normalised(name: str) -> bytes:
        raw = (FIXTURE_DIR / name).read_bytes()
        return raw.replace(b'\r\n', b'\n').replace(b'\r', b'\n')

    base = normalised('mock.frd')
    assert normalised('mock_crlf.frd') == base
    assert normalised('mock_cr.frd') == base


def test_the_signed_zero_fixture_still_has_signed_zeros():
    """A fixture that exists for one byte sequence must still contain it.

    ``signed_zero.frd`` was added because a sweep over CalculiX's own
    regression suite found 21 files containing ``-0.00000E+00`` and none in
    this repository. It is the only fixture that can fail
    ``assert_bitwise_equal`` for a dropped sign, so an editor or a formatter
    quietly rewriting ``-0.00000E+00`` as ``0.00000E+00`` would remove the
    suite's only coverage of that bug while leaving every test green.
    """
    raw = (FIXTURE_DIR / 'signed_zero.frd').read_bytes()
    assert raw.count(b'-0.00000E+00') >= 5, (
        'signed_zero.frd has lost its negative zeros; assert_bitwise_equal now '
        'has nothing in the corpus that would exercise the sign of a zero'
    )


def test_the_nan_fixture_still_has_nans():
    """Likewise for the NaN coordinates CalculiX writes for network nodes."""
    raw = (FIXTURE_DIR / 'nan_coords.frd').read_bytes()
    assert raw.count(b'NaN') >= 3, 'nan_coords.frd has lost its NaN records'
